// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2WQkN5fm2UmYzZ2-iok6W3FMGjbibEtg',
    appId: '1:1091805794952:web:80fe39436d0599caa8c53d',
    messagingSenderId: '1091805794952',
    projectId: 'miniprojet-830fd',
    authDomain: 'miniprojet-830fd.firebaseapp.com',
    storageBucket: 'miniprojet-830fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDog5RAjw73tE2APBKH63svARK2wdcbsjc',
    appId: '1:1091805794952:android:eeb451eda06fb495a8c53d',
    messagingSenderId: '1091805794952',
    projectId: 'miniprojet-830fd',
    storageBucket: 'miniprojet-830fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGOaMD8OJA8YnzSRc3FBKrPY-RtbIc1DM',
    appId: '1:1091805794952:ios:a472374d5af3c2c6a8c53d',
    messagingSenderId: '1091805794952',
    projectId: 'miniprojet-830fd',
    storageBucket: 'miniprojet-830fd.appspot.com',
    iosClientId: '1091805794952-udvph14oanigt0m9ct2tdb3d18kg380r.apps.googleusercontent.com',
    iosBundleId: 'com.example.survey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGOaMD8OJA8YnzSRc3FBKrPY-RtbIc1DM',
    appId: '1:1091805794952:ios:a472374d5af3c2c6a8c53d',
    messagingSenderId: '1091805794952',
    projectId: 'miniprojet-830fd',
    storageBucket: 'miniprojet-830fd.appspot.com',
    iosClientId: '1091805794952-udvph14oanigt0m9ct2tdb3d18kg380r.apps.googleusercontent.com',
    iosBundleId: 'com.example.survey',
  );
}
